import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const api=(path,opt={})=>fetch('/api'+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.token||''}`}}).then(async r=>{if(!r.ok)throw Error((await r.json()).detail||'Request failed');return r.json()});
function Login({onLogin}){const [email,setEmail]=useState('admin@pleasantpalace.local'),[password,setPassword]=useState('admin123'),[err,setErr]=useState('');const submit=async e=>{e.preventDefault();try{let body=new URLSearchParams({username:email,password});let r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw Error('Invalid credentials');let x=await r.json();localStorage.token=x.access_token;onLogin()}catch(e){setErr(e.message)}};return <div className="login"><form onSubmit={submit}><h1>🏢 Society Manager</h1><p>Administrator Login</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button>Login</button>{err&&<div className="error">{err}</div>}<small>Default: admin@pleasantpalace.local / admin123</small></form></div>}
function App(){const [logged,setLogged]=useState(!!localStorage.token),[tab,setTab]=useState('Dashboard');if(!logged)return <Login onLogin={()=>setLogged(true)}/>;const logout=()=>{localStorage.clear();setLogged(false)};return <div className="app"><aside><h2>🏢 Society</h2>{['Dashboard','Members','Maintenance','Expenses','Complaints','Notices'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}<button className="logout" onClick={logout}>Logout</button></aside><main><header><h1>{tab}</h1><span>Admin</span></header>{tab==='Dashboard'&&<Dashboard/>}{tab==='Members'&&<Members/>}{tab==='Maintenance'&&<Maintenance/>}{tab==='Expenses'&&<Expenses/>}{tab==='Complaints'&&<Complaints/>}{tab==='Notices'&&<Notices/>}</main></div>}
function Dashboard(){const [d,setD]=useState(null);useEffect(()=>{api('/dashboard').then(setD)},[]);if(!d)return <p>Loading...</p>;return <><div className="cards"><Card t="Flats / Members" v={d.members}/><Card t="Collected" v={'₹'+d.collected.toLocaleString()}/><Card t="Pending" v={'₹'+d.pending.toLocaleString()}/><Card t="Expenses" v={'₹'+d.expenses.toLocaleString()}/><Card t="Open Complaints" v={d.open_complaints}/></div><div className="panel"><h2>Society Overview</h2><p>Maintenance collected: <b>₹{d.collected.toLocaleString()}</b> of ₹{d.maintenance_total.toLocaleString()}</p><div className="bar"><i style={{width:(d.maintenance_total?d.collected/d.maintenance_total*100:0)+'%'}}/></div></div></>}
function Card({t,v}){return <div className="card"><small>{t}</small><strong>{v}</strong></div>}
function Members(){const [rows,setRows]=useState([]),[form,setForm]=useState({flat_no:'',name:'',phone:'',email:'',resident_type:'Owner',parking:''});const load=()=>api('/members').then(setRows);useEffect(load,[]);const add=async e=>{e.preventDefault();await api('/members',{method:'POST',body:JSON.stringify(form)});setForm({flat_no:'',name:'',phone:'',email:'',resident_type:'Owner',parking:''});load()};return <><form className="inline-form" onSubmit={add}>{Object.keys(form).map(k=><input placeholder={k.replace('_',' ')} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<button>Add</button></form><Table headers={['Flat','Name','Phone','Email','Type','Parking']} rows={rows.map(x=>[x.flat_no,x.name,x.phone,x.email,x.resident_type,x.parking])}/></>}
function Maintenance(){const [rows,setRows]=useState([]);const load=()=>api('/maintenance').then(setRows);useEffect(load,[]);return <Table headers={['Flat','Resident','Month','Amount','Status','Action']} rows={rows.map(x=>[x.flat_no,x.name,x.month,'₹'+x.amount,x.status,x.status==='PENDING'?<button onClick={async()=>{await api('/maintenance/'+x.id+'/pay',{method:'POST'});load()}}>Mark Paid</button>:'✓'])}/>}
function Expenses(){const [rows,setRows]=useState([]),[f,setF]=useState({category:'',description:'',amount:'',expense_date:new Date().toISOString().slice(0,10)});const load=()=>api('/expenses').then(setRows);useEffect(load,[]);const add=async e=>{e.preventDefault();await api('/expenses',{method:'POST',body:JSON.stringify({...f,amount:+f.amount})});setF({...f,category:'',description:'',amount:''});load()};return <><form className="inline-form" onSubmit={add}>{Object.keys(f).map(k=><input type={k==='amount'?'number':k==='expense_date'?'date':'text'} placeholder={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/ >)}<button>Add Expense</button></form><Table headers={['Category','Description','Amount','Date']} rows={rows.map(x=>[x.category,x.description,'₹'+x.amount,x.expense_date])}/></>}
function Complaints(){const [rows,setRows]=useState([]),[f,setF]=useState({member_id:'',title:'',description:''});const load=()=>api('/complaints').then(setRows);useEffect(load,[]);const add=async e=>{e.preventDefault();await api('/complaints',{method:'POST',body:JSON.stringify({...f,member_id:f.member_id?+f.member_id:null})});setF({member_id:'',title:'',description:''});load()};const update=async(id,status)=>{await api('/complaints/'+id,{method:'PATCH',body:JSON.stringify({status})});load()};return <><form className="inline-form" onSubmit={add}><input placeholder="Member ID (optional)" value={f.member_id} onChange={e=>setF({...f,member_id:e.target.value})}/><input placeholder="Title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><input placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><button>Add Complaint</button></form><Table headers={['Flat','Title','Description','Status','Action']} rows={rows.map(x=>[x.flat_no,x.title,x.description,x.status,<select value={x.status} onChange={e=>update(x.id,e.target.value)}><option>OPEN</option><option>IN_PROGRESS</option><option>RESOLVED</option></select>])}/></>}
function Notices(){const [rows,setRows]=useState([]),[f,setF]=useState({title:'',content:''});const load=()=>api('/notices').then(setRows);useEffect(load,[]);const add=async e=>{e.preventDefault();await api('/notices',{method:'POST',body:JSON.stringify(f)});setF({title:'',content:''});load()};return <><form className="inline-form" onSubmit={add}><input placeholder="Title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><input placeholder="Notice content" value={f.content} onChange={e=>setF({...f,content:e.target.value})}/><button>Publish</button></form><Table headers={['Title','Content','Date']} rows={rows.map(x=>[x.title,x.content,new Date(x.created_at).toLocaleString()])}/></>}
function Table({headers,rows}){return <div className="panel"><table><thead><tr>{headers.map(h=><th>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<p>No records found.</p>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
